[tool.poetry]
name = "m5stack-practice"
version = "0.1.0"
description = ""
authors = ["molmol-Lab <cmt13032@nitech.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
